[package]
name = "kloonorio"
version = "0.1.0"
authors = ["Simon Voordouw <simonvoordouw@gmail.com>"]
edition = "2021"

[dependencies]
bevy_ecs_tilemap = "*"
tracing = "*"
tracing-subscriber = "*"
mockall = "*"
bevy_egui = "*"
bevy = { version = "0.6" , features = ["wayland"]}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
