[package]
name = "kloonorio"
version = "0.1.0"
authors = ["Simon Voordouw <simonvoordouw@gmail.com>"]
edition = "2018"

[dependencies]
bevy_tilemap = "*"
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
mockall = "0.9.1"
bevy_egui = "*"
bevy = "*"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
